### ISSUE TITLE
Database in clamav/clamav:latest docker image is out of date

### ISSUE THREAD

**Issue by mrdziuban** [Cisco-Talos/clamav#966] opened 2023-06-27 17:02 UTC
Describe the bug
----------------

The database in the `clamav/clamav:latest` docker image is from May 1.

I see there's [a GitHub workflow](https://github.com/Cisco-Talos/clamav/blob/main/.github/workflows/docker-db-update.yml) configured to update it once a month, but the `dockerfiles/update_db_image.sh` script it references was removed in November 2022 -- https://github.com/Cisco-Talos/clamav/commit/2f0189759e607d046707e66ddab40e510e67e605 -- and the new repository to build docker images (https://github.com/Cisco-Talos/clamav-docker) doesn't have a similar update process.

How to reproduce the problem
----------------------------

```bash
$ docker run -it --rm --entrypoint sh clamav/clamav:latest

# in docker container
$ ls -l /var/lib/clamav/
total 226584
-rw-r--r--    1 clamav   clamav      291965 May  1 20:46 bytecode.cvd
-rw-r--r--    1 clamav   clamav    61241662 May  1 20:46 daily.cvd
-rw-r--r--    1 clamav   clamav   170479789 May  1 20:46 main.cvd
```

**Comment by mrdziuban** [comment] 2023-06-27 17:12
Forgot to mention, running `freshclam` in the docker container says that the database is 59 versions behind

**Comment by micahsnyder** [comment] 2023-07-12 23:21
This is expected behavior. You still need to run freshclam on this image to apply those 59 patches to get it up to date.  It is still much less data usage than downloading the whole databases from scratch.

It would probably be good if we updated our images once a month, or even once a week.   But we don't have plans at this time to do it daily. 

I'll bring it up in our next team meeting to figure out how best we can automate updates to the image, because regular updates will certainly help to resolve CVE's in the base image without requiring me to manually do it.

**Comment by rjmcnamara** [comment] 2024-04-11 21:33
@micahsnyder any update on that?    Releasing a new image when there' s a false positive removed from the database is kinda critical for those of us using clamav in a pipeline.

**Comment by micahsnyder** [comment] 2024-04-11 21:52
We build new images approximately once a week now.  You are responsible for ensuring that freshclam is used to update the database in the container.  By default, the container runs the freshclam daemon process so it gets updates the same day that updates are published online. 

I forgot to close this ticket, but it is not a bug/issue.  It is working as intended.

**Closed by micahsnyder** 2024-04-11 21:52 UTC

**Comment by micahsnyder** [comment] 2024-04-11 21:59
@rjmcnamara A solution we recommend is to use the `_base` version of the docker images and mount a volume with the databases.  This way the image download is lightweight, and you can spin up a new container which has the same databases as the previous container.   I'm not familiar with how to set up volumes in k8s, but at least with regular docker we have some instructions to help get you started if you want to try it https://docs.clamav.net/manual/Installing/Docker.html#persisting-the-virus-database-volume

**Comment by rjmcnamara** [comment] 2024-04-11 23:25
Thanks @micahsnyder I considered mounting a volume as you described (and it does work locally of course) but I'm using the image from a github workflow -- not in a persistent runner or with any way to create a persistent volume.   Whitelist was plan B (won't work for the same reason).   Plan C is to build the images myself  and store them in Artifactory along with a signature database updated by `update_db_image.sh`.

...starting to get a bit off track here 😁

**Comment by micahsnyder** [comment] 2024-04-12 02:42
@rjmcnamara I haven't tried using the image from a github workflow before.  But at least when you start the image, it should run freshclam before starting clamd to update the out-of-date database to the latest versions, then start clamd.  If you're not running the image though and you're just executing clamscan directly from it, then yeah the databases will be out of date.
