### ISSUE TITLE
ClamAV Conf.

### ISSUE THREAD

**Issue by karascho** [Cisco-Talos/clamav#1410] opened 2024-11-23 14:58 UTC
1.What is the command line in the terminal to exclude directories.
Please with examples.
2. The same question for maldetect
3. Is there a option to get back to the original configuration after fail configuration.

This should not be so extremly compliclate for user who dont have studied
computer science but just an option to dig deeper.

I'm unsure about the system here. Is this a new ticket or just a comment?

**Comment by micahsnyder** [comment] 2024-11-23 16:06
This is a new ticket. Will close as duplicate of #1409

**Closed by micahsnyder** 2024-11-23 16:06 UTC
