### ISSUE TITLE
Spurious rate limiting for freshclam

### ISSUE THREAD

**Issue by msapiro** [Cisco-Talos/clamav#588] opened 2022-05-20 14:01 UTC
Describe the bug
----------------

When freshclam gets an error because of an issue with the CDN it retries several times ultimately resulting in a rate limiting 24 hour cool down.

How to reproduce the problem
----------------------------

Run freshclam when there is an error from the CDN. See the freshclam log excerpt below.

```
# clamconf -n
Checking configuration files in /etc/clamav

Config file: clamd.conf
-----------------------
PreludeAnalyzerName = "ClamAV"
LogFile = "/var/log/clamav/clamav.log"
LogFileMaxSize = "4294967295"
LogTime = "yes"
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
LocalSocket = "/var/run/clamav/clamd.ctl"
LocalSocketGroup = "clamav"
LocalSocketMode = "666"
MaxConnectionQueueLength = "15"
MaxThreads = "12"
ReadTimeout = "180"
SendBufTimeout = "200"
SelfCheck = "3600"
User = "clamav"
BytecodeTimeout = "60000"
MaxScanTime = "120000"
MaxRecursion = "16"
PCREMatchLimit = "10000"
PCRERecMatchLimit = "5000"

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "4294967295"
LogTime = "yes"
LogRotate = "yes"
UpdateLogFile = "/var/log/clamav/freshclam.log"
Checks = "24"
DatabaseMirror = "db.local.clamav.net", "database.clamav.net"
MaxAttempts = "5"
ReceiveTimeout = "30"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.103.6
Optional features supported: MEMPOOL IPv6 FRESHCLAM_DNS_FIX AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON 

Database information
--------------------
Database directory: /var/lib/clamav
[3rd Party] rfxn.ndb: 2039 sigs
[3rd Party] winnow_malware.hdb: 1 sig 
[3rd Party] interserver256.hdb: 17555 sigs
[3rd Party] winnow_phish_complete_url.ndb: 54 sigs
[3rd Party] rfxn.hdb: 12946 sigs
[3rd Party] badmacro.ndb: 627 sigs
[3rd Party] spamattach.hdb: 14 sigs
[3rd Party] hackingteam.hsb: 435 sigs
[3rd Party] spam_marketing.ndb: 31016 sigs
[3rd Party] winnow_malware_links.ndb: 133 sigs
[3rd Party] bofhland_phishing_URL.ndb: 72 sigs
[3rd Party] phish.ndb: 28302 sigs
[3rd Party] bofhland_malware_attach.hdb: 1836 sigs
[3rd Party] Sanesecurity_spam.yara: 46 sigs
[3rd Party] malwarehash.hsb: 771 sigs
[3rd Party] EK_BleedingLife.yar: 112 sigs
[3rd Party] jurlbl.ndb: 5519 sigs
[3rd Party] securiteinfopdf.hdb: 3408 sigs
[3rd Party] junk.ndb: 55925 sigs
[3rd Party] blurl.ndb: 3030 sigs
[3rd Party] rogue.hdb: 2711 sigs
[3rd Party] securiteinfohtml.hdb: 63744 sigs
[3rd Party] securiteinfoascii.hdb: 103946 sigs
[3rd Party] winnow_bad_cw.hdb: 1 sig 
[3rd Party] sigwhitelist.ign2: 14 sigs
[3rd Party] malwarepatrol.db: 30479 sigs
[3rd Party] sanesecurity.ftm: 184 sigs
[3rd Party] securiteinfoandroid.hdb: 84401 sigs
[3rd Party] phishtank.ndb: 4588 sigs
[3rd Party] rfxn.yara: 11527 sigs
main.cld: version 62, sigs: 6647427, built on Thu Sep 16 05:32:42 2021
[3rd Party] securiteinfo.hdb: 97021 sigs
[3rd Party] bofhland_cracked_URL.ndb: 40 sigs
[3rd Party] winnow.attachments.hdb: 1 sig 
[3rd Party] securiteinfo.ign2: 128 sigs
[3rd Party] foxhole_generic.cdb: 212 sigs
[3rd Party] scam.ndb: 12813 sigs
[3rd Party] WShell_ASPXSpy.yar: 21 sigs
[3rd Party] whitelist.fp: 3081 sigs
[3rd Party] spamimg.hdb: 208 sigs
[3rd Party] WShell_Drupalgeddon2_icos.yar: 26 sigs
[3rd Party] porcupine.hsb: 215 sigs
[3rd Party] local.ign2: 5 sigs
[3rd Party] javascript.ndb: 43708 sigs
daily.cld: version 26546, sigs: 1984482, built on Thu May 19 01:03:47 2022
[3rd Party] Sanesecurity_sigtest.yara: 54 sigs
[3rd Party] bofhland_malware_URL.ndb: 4 sigs
[3rd Party] foxhole_filename.cdb: 2843 sigs
[3rd Party] winnow_extended_malware.hdb: 1 sig 
[3rd Party] urlhaus.ndb: 5601 sigs
bytecode.cld: version 333, sigs: 92, built on Mon Mar  8 07:21:51 2021
[3rd Party] porcupine.ndb: 7121 sigs
Total number of signatures: 9270540

Platform information
--------------------
uname: Linux 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
Full OS version: Ubuntu 20.04.4 LTS
zlib version: 1.2.11 (1.2.11), compile flags: a9
platform id: 0x0a217f7f0800000000090400

Build information
-----------------
GNU C: 9.4.0 (9.4.0)
CPPFLAGS: -Wdate-time -D_FORTIFY_SOURCE=2
CFLAGS: -g -O2 -fdebug-prefix-map=/build/clamav-1RbSOK/clamav-0.103.6+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS: -g -O2 -fdebug-prefix-map=/build/clamav-1RbSOK/clamav-0.103.6+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64
LDFLAGS: -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
Configure: '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-1RbSOK/clamav-0.103.6+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-1RbSOK/clamav-0.103.6+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed' '--with-dbdir=/var/lib/clamav' '--sysconfdir=/etc/clamav' '--disable-clamav' '--disable-unrar' '--enable-milter' '--enable-dns-fix' '--with-libjson' '--with-system-libmspack' '--with-libcurl=/usr' '--with-gnu-ld' '--with-systemdsystemunitdir=/lib/systemd/system' 'build_alias=x86_64-linux-gnu' 'OBJCFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-1RbSOK/clamav-0.103.6+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security'
sizeof(void*) = 8
Engine flevel: 127, dconf: 127
```

Attachments
-----------
Excerpt from freshclam log.
```
Thu May 19 13:34:45 2022 -> Received signal: wake up
Thu May 19 13:34:45 2022 -> ClamAV update process started at Thu May 19 13:34:45 2022
Thu May 19 13:34:45 2022 -> WARNING: DNS record is older than 3 hours.
Thu May 19 13:34:45 2022 -> Trying to retrieve CVD header from https://database.clamav.net/daily.cvd
Thu May 19 13:34:45 2022 -> daily.cld database is up-to-date (version: 26546, sigs: 1984482, f-level: 90, builder: raynman)
Thu May 19 13:34:45 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:34:45 2022 -> WARNING: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:34:45 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:34:45 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:34:45 2022 -> Trying again in 5 secs...
Thu May 19 13:34:50 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:34:51 2022 -> WARNING: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:34:51 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:34:51 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:34:51 2022 -> Trying again in 5 secs...
Thu May 19 13:34:56 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:34:56 2022 -> WARNING: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:34:56 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:34:56 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:34:56 2022 -> Trying again in 5 secs...
Thu May 19 13:35:01 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:35:01 2022 -> WARNING: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:35:01 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:35:01 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:35:01 2022 -> Trying again in 5 secs...
Thu May 19 13:35:06 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:35:06 2022 -> ERROR: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:35:06 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:35:06 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:35:06 2022 -> Giving up on https://database.clamav.net...
Thu May 19 13:35:06 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:35:06 2022 -> WARNING: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:35:06 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:35:06 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:35:06 2022 -> Trying again in 5 secs...
Thu May 19 13:35:11 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:35:11 2022 -> WARNING: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:35:11 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:35:11 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:35:11 2022 -> Trying again in 5 secs...
Thu May 19 13:35:16 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:35:16 2022 -> WARNING: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:35:16 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:35:16 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:35:16 2022 -> Trying again in 5 secs...
Thu May 19 13:35:21 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:35:21 2022 -> WARNING: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:35:21 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:35:21 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:35:21 2022 -> Trying again in 5 secs...
Thu May 19 13:35:26 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 19 13:35:26 2022 -> ERROR: remote_cvdhead: Malformed CVD header (too short)
Thu May 19 13:35:26 2022 -> WARNING: Failed to get main database version information from server: https://database.clamav.net
Thu May 19 13:35:26 2022 -> ERROR: check_for_new_database_version: Failed to find main database using server https://database.clamav.net.
Thu May 19 13:35:26 2022 -> Giving up on https://database.clamav.net...
Thu May 19 13:35:26 2022 -> ERROR: Update failed for database: main
Thu May 19 13:35:26 2022 -> ERROR: Database update process failed: HTTP GET failed
Thu May 19 13:35:26 2022 -> ERROR: Update failed.
Thu May 19 13:35:26 2022 -> --------------------------------------
Thu May 19 14:35:26 2022 -> Received signal: wake up
Thu May 19 14:35:26 2022 -> ClamAV update process started at Thu May 19 14:35:26 2022
Thu May 19 14:35:26 2022 -> WARNING: FreshClam previously received error code 429 or 403 from the ClamAV Content Delivery Network (CDN).
Thu May 19 14:35:26 2022 -> This means that you have been rate limited or blocked by the CDN.
Thu May 19 14:35:26 2022 ->  1. Verify that you're running a supported ClamAV version.
Thu May 19 14:35:26 2022 ->     See https://docs.clamav.net/faq/faq-eol.html for details.
Thu May 19 14:35:26 2022 ->  2. Run FreshClam no more than once an hour to check for updates.
Thu May 19 14:35:26 2022 ->     FreshClam should check DNS first to see if an update is needed.
Thu May 19 14:35:26 2022 ->  3. If you have more than 10 hosts on your network attempting to download,
Thu May 19 14:35:26 2022 ->     it is recommended that you set up a private mirror on your network using
Thu May 19 14:35:26 2022 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Thu May 19 14:35:26 2022 ->     CDN and your own network.
Thu May 19 14:35:26 2022 ->  4. Please do not open a ticket asking for an exemption from the rate limit,
Thu May 19 14:35:26 2022 ->     it will not be granted.
Thu May 19 14:35:26 2022 -> WARNING: You are still on cool-down until after: 2022-05-20 13:35:06
Thu May 19 14:35:26 2022 -> --------------------------------------
```

**Comment by tontonsonic** [comment] 2022-05-24 05:59
Faced the same problem a few days ago - we witnessed 2 updates tentatives ending up with : WARNING remote_cvdhead: Malformed CVD header (too short) (maybe due to a proxy problem), which then triggered the rate limitation and cool-down period.

**Comment by msapiro** [comment] 2022-05-24 21:17
I tried changing the setting for MaxAttempts in freshclam.conf from 5 to 2, but that seemed to make no difference.

**Comment by micahsnyder** [comment] 2022-05-27 19:40
@msapiro @tontonsonic can you tell me where you got your clamav packages?  From my research on this so far it appears it may be a package-specific issue caused by the clamav build failing to detect `libresolv` and then building without DNS support.  I'd like to track down which packages are impacted to see if I can work with the maintainers to get them fixed.  And in some future clamav patch version we can change it so clamav can't be built without DNS support.

**Comment by msapiro** [comment] 2022-05-27 20:25
I am using the Ubuntu package currently 0.103.6+dfsg-0ubuntu0.20.04.1

**Comment by tontonsonic** [comment] 2022-05-30 12:34
on my side 
```
#yum info clamav.x86_64
Loaded plugins: langpacks, versionlock
Installed Packages
Name        : clamav
Arch        : x86_64
Version     : 0.103.4
Release     : 1.el7
Size        : 12 M

```

**Comment by micahsnyder** [comment] 2022-05-31 18:50
My suspicion about DNS being disabled in the new packages was incorrect. I confirmed that using DNS for the CVD version checks is working in the EPEL and ubuntu 0.103.6 packages. I'm still unsure why a number of people saw it attempt to download the CVD header for the version check instead of using the DNS entry or why cloudflare wasn't serving the entire CVD header for `main.cvd` or `daily.cvd` when requested. 

Anyways... last week we also cleared cloudflare's cache of the `main.cvd` and `daily.cvd` files. I haven't heard any new complaints since then on this issue.

@msapiro @tontonsonic are you still having issues or does it appear to be working again?

**Comment by msapiro** [comment] 2022-05-31 19:31
It is currently working for me. Last issue was seen Wed May 25 20:04:54 2022 -0700

**Comment by micahsnyder** [comment] 2022-06-02 17:01
It looks to me like the event where cloudflare was serving up smaller files requested which was causing freshclam to retry and then get rate-limited has been resolved.  I'm going to close this issue.

If you observe this message again in advance of rate limiting:
`WARNING: remote_cvdhead: Malformed CVD header (too short)`
then feel free to re-open the issue.

**Closed by micahsnyder** 2022-06-02 17:01 UTC
