### ISSUE TITLE
Provide multi-arch official docker images

### ISSUE THREAD

**Issue by strelok1** [Cisco-Talos/clamav#536] opened 2022-04-07 16:44 UTC
Describe the bug
----------------

Official images are only linux/amd64. When run on an M1 Mac or another ARM host you get a warning:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
It should be possible to build multi-arch images using `docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 ...`

How to reproduce the problem
----------------------------

```
$ docker pull clamav/clamav
$ docker manifest inspect --verbose clamav/clamav
```
Only one manifest entry for linux/amd64
<img width="898" alt="image" src="https://user-images.githubusercontent.com/2357295/162253854-1b09f4dd-a297-43d7-900b-112cdb828d7e.png">

If I build an image from the Dockerfile in this repo with a recent build of Docker for Mac, for example, a multi-arch image is created that can be run on M1 Macs and other ARM arch hosts, such as latest generation cloud instances from all the major cloud providers:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/2357295/162254417-f1fa4bf5-3f41-409f-82a6-0059579352e5.png">

**Comment by micahsnyder** [comment] 2022-04-07 17:14
This feels like a duplicate of https://github.com/Cisco-Talos/clamav/issues/482

Your recommendation on how to do the build will be useful for us to modify our build tooling in Jenkins. If you have any further clarification on how to run the `buildx` command, the details will be helpful.

**Closed by micahsnyder** 2022-04-07 17:14 UTC
