### ISSUE TITLE
Azure Container Instances - Initial setup not working until clamd restart

### ISSUE THREAD

**Issue by M1K3Yio** [Cisco-Talos/clamav#567] opened 2022-05-02 15:46 UTC
Describe the bug
----------------

I am clamav using Azure Container instances.  They're a two issues I've noticed that I am trying to track down.  Maybe the solution is as easy as needing a proper restart policy.

Here's what I've been noticing.  Using Azure Portal or Bicep(Which is what I will be using in our pipeline).  The container is created with no issues, but unable to contact server.  The only way around this is if I connect to the container and run `clamd restart` then we can connect just fine.  Also, occasionally connection seems to stop and I need to restart again.

This is possibly an issue with the Dockerfile and support with Azure Container Instances?

How to reproduce the problem
----------------------------

Within Azure Portal

Create a new Container instance
Basic
Image source: Other repository
Image type: Public
Image: `clamav/clamav:latest`
OS type: Lunux
Size: 1 vcpu, 2 GIB

Networking
Private
Select Subscription Virtual network/Subnet
Ports: 3310 TCP

Advanced
I have nothing here, but I have a feeling this is where I would need a command to handle this issue maybe.

Then Create image.

Once container is running, if you connect via /bin/sh
Run `clamdcheck.sh`
ERROR: Unable to contact server
Run `clamd restart`
Run `clamdcheck.sh`
Clamd is up

**Comment by kim3er** [comment] 2022-09-05 15:45
I'm seeing this behaviour as well on Azure Container Instances, using clamav:stable. 1 CPU, 1.5 GiB Memory.

**Comment by micahsnyder** [comment] 2022-09-05 22:14
I suspect the issue is that you need more RAM, at least 3GB. Or else provide a clamd.conf with ConcurrentReload disabled. The default behavior is to reload the database after an update while continuing to scan. At present the loaded databases use a lot of memory and with only 1.5GB or even 2GB I expect it will cause the clamd to crash and the container to be unresponsive.

**Comment by kim3er** [comment] 2022-09-06 08:17
Hi @micahsnyder! Thank you for your response, 3GB was the magic number, socket working fine now.

**Comment by micahsnyder** [comment] 2022-09-06 18:50
Great! 

I think we can close this issue.  @M1K3Yio issue would have been the same.  As mentioned in #571, this issue is also a duplicate of https://github.com/Cisco-Talos/clamav/issues/330 where the same problem and solution are discussed.

**Closed by micahsnyder** 2022-09-06 18:50 UTC
