### ISSUE TITLE
LibClamAV Error for ClamAV 1.0.4 for EL9

### ISSUE THREAD

**Issue by brandonrace** [Cisco-Talos/clamav#1107] opened 2023-12-04 20:34 UTC
Describe the bug
----------------

When we try and run a clamscan with ClamAV 1.0.4 for Enterprise Linux 9, we are running into the below errors.  This works fine for us  when using ClamAV 1.0.3 for Enterprise Linux 8.  

LibClamAV Error: Can't load /var/lib/clamav/daily.cvd: Can't allocate memory
LibClamAV Error: cli_loaddbdir: error loading database /var/lib/clamav/daily.cvd
ERROR: Can't allocate memory

How to reproduce the problem
----------------------------

mkdir -p /tmp/test_virus
echo 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > /tmp/test_virus/virus
sudo clamscan /tmp/test_virus

**Comment by brandonrace** [comment] 2023-12-04 20:39
![EL8](https://github.com/Cisco-Talos/clamav/assets/69923753/bffc6740-ce02-433d-a811-d23a3a21c26f)
![EL9](https://github.com/Cisco-Talos/clamav/assets/69923753/47acfe78-8456-465e-87c2-a4546587610b)

**Comment by brandonrace** [comment] 2023-12-04 20:39
![EL8](https://github.com/Cisco-Talos/clamav/assets/69923753/fe9831da-ed1b-4c30-8648-2869697f5d6b)
![EL9](https://github.com/Cisco-Talos/clamav/assets/69923753/77425f67-3035-4cd7-9e86-3c90feed5114)

**Comment by micahsnyder** [comment] 2023-12-05 23:09
@brandonrace how much RAM does your machine have?

**Comment by brandonrace** [comment] 2023-12-07 18:09
Nearly 7GB is free, I agree that "can't allocate memory" sounds like it would be a RAM issue but I don't think that's the case.  Are using the same m5.large instance in AWS for both RHEL-8 and RHEL-9, for the EL8 version of ClamAV, we don't have any issues, with the EL9 version, we get the error I sent.

**Comment by micahsnyder** [comment] 2023-12-07 18:17
Yeah it doesn't sound like a RAM issue. I wonder if the daily.cvd file got corrupted somehow.  Can you try deleting it and then running freshclam to download a new copy?

**Comment by brandonrace** [comment] 2023-12-07 18:27
![Bytecode](https://github.com/Cisco-Talos/clamav/assets/69923753/f96de5f3-8457-40a9-bb77-6a0a4929052b)
I just ran another test and this time instead of loading the daily.cvd file it can't load the bytecode.cvd file, so it doesn't seem like an issue with one particular file.  Have you been able to reproduce this error?

**Comment by brandonrace** [comment] 2023-12-07 18:29
I also get the can't allocate memory error when running freshclam.

**Comment by brandonrace** [comment] 2023-12-07 18:54
I also noticed that when the clamscan command is ran the line that says Loading gets to 2.03M/8.70M before crashing and giveing the can't allocate memory error.

**Comment by micahsnyder** [comment] 2023-12-07 19:47
I was unable to reproduce the error.

I don't have access to RHEL9. I just tested with a docker container using `rockylinux:9`. 
How did you install ClamAV? I used these instructions:
https://docs.clamav.net/manual/Installing/Packages.html#epel-fedora-rhel-and-centos

**Comment by brandonrace** [comment] 2023-12-11 16:29
I also wanted to add that our /var/log/clamd.log file is spammed with the same "Can't allocate memory error".  Is there anywhere else I'd be able to find a more helpful output?


![clamd](https://github.com/Cisco-Talos/clamav/assets/69923753/f985265f-afe4-44c0-a43d-76981cd5cc44)

**Comment by micahsnyder** [comment] 2023-12-11 19:39
I'm glad to hear you solved it.  I'll go ahead and close this then.  

Sorry no update on when we can support FIPS.  To do it, we need to modernize how we sign the clamav CVD database archives and CDIFF database archive patch files.  We have started planning it, but my teammate who is expected to work on it is still working on clamav-adjacent internal project and I'm unsure when he will be able to switch to work on this.

**Closed by micahsnyder** 2023-12-11 19:39 UTC
