### ISSUE TITLE
clamav image is amd64 only.  Will an aarch64 version be released?

### ISSUE THREAD

**Issue by millerthegorilla** [Cisco-Talos/clamav#512] opened 2022-03-20 18:57 UTC
Describe the bug
----------------

When starting the clamav container using systemd, an error is produced stating ```{"msg":"exec container process `/init`: Exec format error","level":"error","time":"2022-03-20T18:00:00.000838151Z"}'''

Tinternet reckons that it is a byte order mark error, which makes sense, as it has probably been compiled on a different architecture.  I am running coreos on a pi4, and am unable currently to mount the image to examine it to be certain.   Answer one explains how to examine the file to see the bom problem.
```https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error```

How to reproduce the problem
----------------------------

start a clamav image using podman or systemctl on a coreos pi4b.

**Comment by millerthegorilla** [comment] 2022-03-21 14:04
Ok, I was able to examine the file and it has no BOM on the init script.   It does use ```tini``` though, so I wonder if that is what is causing the issue.
Are there any plans to create a clamav container specifically for aarc64?

**Comment by micahsnyder** [comment] 2022-04-12 17:34
Yes, I would like to build them as multi arch images.  Just need to find time to make the required changes.

This is a duplicate of https://github.com/Cisco-Talos/clamav/issues/482

**Closed by micahsnyder** 2022-04-12 17:34 UTC
