### ISSUE TITLE
File path check failure: Result too large or too small. ERROR

### ISSUE THREAD

**Issue by ColinDexter** [Cisco-Talos/clamav#426] opened 2022-01-15 12:26 UTC
Hi,

I get the following error “File path check failure: Result too large or too small. ERROR” when a file name contains chars like € ñ ë ñ 

I use the clamav-0.104.2.win.x64 version. In version 0.103.x it worked without any problems.

Regards,
Colin

**Comment by delta-centauri** [comment] 2022-01-28 09:52
Hi Colin, I'm having the same issue. Did you find a solution?

**Comment by micahsnyder** [comment] 2022-01-28 21:41
I think this is a duplicate of #418.  When I tested it the file was still scanned despite the error, not that we shouldn't fix this.

**Comment by ragusaa** [comment] 2024-03-25 18:16
This appears to be fixed, please re-open if you are still having issues.

**Closed by ragusaa** 2024-03-25 18:16 UTC
