### ISSUE TITLE
Docker entrypoint uses commands depending on root and is thus not able to be run rootless in kubernetes

### ISSUE THREAD

**Issue by boindil** [Cisco-Talos/clamav#520] opened 2022-03-29 09:29 UTC
The entrypoint should check if it can run the chown/ln command correctly. Otherwise it will just crash.

I am already mounting the path with correct permissions via pvc in kubernetes.
As for the ln: I am now creating that beforehand in a modified Dockerfile.

As it is currently not fully starting up, there seem to be some additional issues, which I am going to comment here.

https://github.com/Cisco-Talos/clamav/blob/b30d9c54b242aee062ae52d93e6714714d591f8e/dockerfiles/docker-entrypoint.sh#L18

https://github.com/Cisco-Talos/clamav/blob/b30d9c54b242aee062ae52d93e6714714d591f8e/dockerfiles/docker-entrypoint.sh#L36

**Comment by mortaelth** [comment] 2022-07-08 12:08
Hello, is there a way to update the official image in order to enable running it as non-root in kubernetes instances?

**Comment by rmueller83** [comment] 2022-07-12 14:39
Duplicate of #478 ?

**Comment by micahsnyder** [comment] 2022-07-12 19:16
> Duplicate of #478 ?

Agreed, looks like a duplicate.  Let's continue this discussion there.

**Closed by micahsnyder** 2022-07-12 19:16 UTC
